name: Pull Request Checks

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black isort pytest pytest-cov requests

      - name: Lint with flake8
        run: |
          flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src/ --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

      - name: Format check with black
        run: |
          black --check src/

      - name: Import sorting check with isort
        run: |
          isort --check-only src/

      - name: Run tests
        run: |
          python -m pytest tests/ -v --cov=src --cov-report=xml

      - name: Comment PR with results
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            const fs = require('fs');
            const testResults = fs.readFileSync('coverage.xml', 'utf8');
            const coverageMatch = testResults.match(/line-rate="([^"]+)"/);
            const coverage = coverageMatch ? Math.round(parseFloat(coverageMatch[1]) * 100) : 0;
            
            const comment = `## PR Check Results ✅
            
            **Code Quality**: ✅ All checks passed
            **Test Coverage**: ${coverage}%
            **Status**: Ready for review
            
            ### Summary:
            - Linting passed
            - Code formatting correct
            - Import sorting correct
            - Tests passed
            - Coverage: ${coverage}%
            
            ---
            *This comment was automatically generated by GitHub Actions*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            }); 